language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- set -o pipefail 
- travis_retry xcodebuild -workspace Example/YTSelectionPopupView.xcworkspace -scheme "YTSelectionPopupView-Example" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty

